### ISSUE TITLE
[MISC] Double check if parse_cigar() can be exchanged by a seqan3 method.

### ISSUE THREAD

**Issue by Irallia** [seqan/iGenVar#85]
We should wait for seqan/seqan3#2502 (done)
Our SeqAn3 library get the update with https://github.com/seqan/iGenVar/pull/91 (done)

**Comment by joshuak94** [comment]
So regarding this, I don't think it's possible to use the `seqan3::detail::parse_cigar` function, because it's part of the protected functions of `format_sam_base`. Maybe someone from the core team can tell us why it's not accessible? It seems to be the exact same function as what @eldariont has in bam_functions.hpp

**Comment by marehr** [comment]
You can inherit `seqan3::detail::format_sam_base` and access `parse_cigar` for now.

I think we can move that functionality into `seqan3/io/sam_file/detail/cigar.hpp`.
