### ISSUE TITLE
iGenVar - Create a Structure for BAM Indexing

### ISSUE THREAD

**Issue by Irallia** [seqan/iGenVar#88]
We have several use cases for indexing a BAM file:
- calculating average read depth of bam file
- calculating read depth around a variant (interval)
- fetching reads around a variant (interval) for genotyping
- ...

For this we need a structure to get the reads of the given interval without going thoug the whole BAM file.
There is the BAI existing, which we could implement in a similar way. We also discussed implementing an interval tree.

EDIT (29.03.2021): We will try to use an interval tree for everything.

**Comment by Irallia** [comment]
@joshuak94 as this is an epic and you already started to work on this. Is it maybe possible to create some issues for this (split this into smaller pieces)? Then we will also see what exactly you are working on and whether there are tasks that can be taken on.
Only if you find the time and it makes sense. 💅 :simple_smile:

**Comment by joshuak94** [comment]
@Irallia Mitra and I are actually pretty close to done! The repository is here: https://github.com/joshuak94/BAMIntervalTree

There are three main hurdles left:
1. We want to store the interval tree which is constructed into a file, so that we don't need to construct it every time.
2. We want to parallelize the construction and/or the searching, both of which are currently done using a single thread.
3. We want to store/use the file offset for the reads to directly return either the file offsets *or* the relevant reads.

Those are also the only three issues in the repository atm :D
